"""Ajout Client Type Affaire et Dossier

Revision ID: 0b4178813094
Revises: 1d95be6556fa
Create Date: 2026-07-12 11:06:45.889541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4178813094'
down_revision: Union[str, Sequence[str], None] = '1d95be6556fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_client', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nin', sa.String(length=50), nullable=True),
    sa.Column('rccm', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_affaire',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossier',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('agence_receptrice_id', sa.Integer(), nullable=False),
    sa.Column('avocat_en_chef_id', sa.Integer(), nullable=False),
    sa.Column('agence_assignee_id', sa.Integer(), nullable=True),
    sa.Column('avocat_assignee_id', sa.Integer(), nullable=True),
    sa.Column('type_affaire_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description_initiale', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('priorite', sa.Integer(), nullable=False),
    sa.Column('date_reception', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_affectation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_cloture', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agence_assignee_id'], ['agence.id'], ),
    sa.ForeignKeyConstraint(['agence_receptrice_id'], ['agence.id'], ),
    sa.ForeignKeyConstraint(['avocat_assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['avocat_en_chef_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['type_affaire_id'], ['type_affaire.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dossier')
    op.drop_table('type_affaire')
    op.drop_table('client')
    # ### end Alembic commands ###
