"""ajout AnalyseIa, doucments, et historiqueAction

Revision ID: 4c9fef9cf64c
Revises: b0f8d45c86d7
Create Date: 2026-07-12 12:07:23.212036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c9fef9cf64c'
down_revision: Union[str, Sequence[str], None] = 'b0f8d45c86d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyse_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('resume_genere', sa.Text(), nullable=False),
    sa.Column('type_detecte', sa.String(length=100), nullable=False),
    sa.Column('mots_cles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agence_suggeree_id', sa.Integer(), nullable=True),
    sa.Column('avocat_suggere_id', sa.Integer(), nullable=True),
    sa.Column('score_confiance', sa.Float(), nullable=False),
    sa.Column('modele_ia', sa.String(length=100), nullable=False),
    sa.Column('validee', sa.Boolean(), nullable=False),
    sa.Column('validee_par', sa.Integer(), nullable=True),
    sa.Column('validee_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agence_suggeree_id'], ['agence.id'], ),
    sa.ForeignKeyConstraint(['avocat_suggere_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ),
    sa.ForeignKeyConstraint(['validee_par'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('chemin_stockage', sa.String(length=500), nullable=False),
    sa.Column('type_mime', sa.String(length=100), nullable=True),
    sa.Column('taille_octets', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidentiel', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historique_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('ancienne_valeur', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nouvelle_valeur', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historique_action')
    op.drop_table('document')
    op.drop_table('analyse_ia')
    # ### end Alembic commands ###
