"""type_affaire&specialite avec des libelle unique 

Revision ID: 6a6fa309b136
Revises: fe40f5e591a7
Create Date: 2026-07-14 16:43:35.248013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6fa309b136'
down_revision: Union[str, Sequence[str], None] = 'fe40f5e591a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'specialite', ['libelle'])
    op.create_unique_constraint(None, 'type_affaire', ['libelle'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'type_affaire', type_='unique')
    op.drop_constraint(None, 'specialite', type_='unique')
    # ### end Alembic commands ###
