"""Ajout de specialite et UserSpecialite(table associative)

Revision ID: b0f8d45c86d7
Revises: 0b4178813094
Create Date: 2026-07-12 11:12:41.029047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0f8d45c86d7'
down_revision: Union[str, Sequence[str], None] = '0b4178813094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_specialite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialite_id', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['specialite_id'], ['specialite.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'specialite_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_specialite')
    op.drop_table('specialite')
    # ### end Alembic commands ###
