"""index sur attributs important et enumeration

Revision ID: d0983a4375fd
Revises: 6a6fa309b136
Create Date: 2026-07-14 22:34:43.363205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0983a4375fd'
down_revision: Union[str, Sequence[str], None] = '6a6fa309b136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

statut_dossier = postgresql.ENUM(
    'EN_ATTENTE', 'EN_COURS',
      'EN_ATTENTE_AFFECTATION', 
      'TERMINE', 
      'ARCHIVE', name='statutdossier', create_type=False)

def upgrade() -> None:
    """Upgrade schema."""
    statut_dossier.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_client_telephone', 'client', ['telephone'], unique=False)
    op.create_unique_constraint(None, 'client', ['email'])
    op.alter_column('dossier', 'statut',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.ENUM('EN_ATTENTE', 'EN_COURS', 'EN_ATTENTE_AFFECTATION', 'TERMINE', 'ARCHIVE', name='statutdossier'),
               existing_nullable=False,
               postgresql_using="statut::statutdossier")
    op.create_index('ix_dossier_client_id', 'dossier', ['client_id'], unique=False)
    op.create_index('ix_dossier_reference', 'dossier', ['reference'], unique=False)
    op.create_index('ix_dossier_statut', 'dossier', ['statut'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dossier_statut', table_name='dossier')
    op.drop_index('ix_dossier_reference', table_name='dossier')
    op.drop_index('ix_dossier_client_id', table_name='dossier')
    op.alter_column('dossier', 'statut',
               existing_type=postgresql.ENUM('EN_ATTENTE', 'EN_COURS', 'EN_ATTENTE_AFFECTATION', 'TERMINE', 'ARCHIVE', name='statutdossier'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               postgresql_using="statut::text")
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_index('ix_client_telephone', table_name='client')
    # ### end Alembic commands ###
