"""modification du nom de des cles avocat_assgnee en enlevant le e muet et aussi pareil pour agence_assignee

Revision ID: e1495a02b906
Revises: 975afff34434
Create Date: 2026-07-12 16:11:06.114805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1495a02b906'
down_revision: Union[str, Sequence[str], None] = '975afff34434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossier', sa.Column('agence_assigne_id', sa.Integer(), nullable=True))
    op.add_column('dossier', sa.Column('avocat_assigne_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('dossier_avocat_assignee_id_fkey'), 'dossier', type_='foreignkey')
    op.drop_constraint(op.f('dossier_agence_assignee_id_fkey'), 'dossier', type_='foreignkey')
    op.create_foreign_key(None, 'dossier', 'agence', ['agence_assigne_id'], ['id'])
    op.create_foreign_key(None, 'dossier', 'user', ['avocat_assigne_id'], ['id'])
    op.drop_column('dossier', 'agence_assignee_id')
    op.drop_column('dossier', 'avocat_assignee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossier', sa.Column('avocat_assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dossier', sa.Column('agence_assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dossier', type_='foreignkey')
    op.drop_constraint(None, 'dossier', type_='foreignkey')
    op.create_foreign_key(op.f('dossier_agence_assignee_id_fkey'), 'dossier', 'agence', ['agence_assignee_id'], ['id'])
    op.create_foreign_key(op.f('dossier_avocat_assignee_id_fkey'), 'dossier', 'user', ['avocat_assignee_id'], ['id'])
    op.drop_column('dossier', 'avocat_assigne_id')
    op.drop_column('dossier', 'agence_assigne_id')
    # ### end Alembic commands ###
