"""mis ajour de client avec des enumeration sur le type!


Revision ID: fe40f5e591a7
Revises: 0f9af067377d
Create Date: 2026-07-14 15:16:12.980579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe40f5e591a7'
down_revision: Union[str, Sequence[str], None] = '0f9af067377d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

clienttype = postgresql.ENUM(
    "PHYSIQUE",
    "MORAL",
    name="clienttype",
)

def upgrade() -> None:
    """Upgrade schema."""
    
    bind = op.get_bind()
    clienttype.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'type_client',
               existing_type=sa.VARCHAR(length=50),
               existing_nullable=False,
               type_=clienttype,
               postgresql_using="type_client::clienttype"
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'type_client',
               existing_type=clienttype,
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
                postgresql_using="role::text"
        )
    # ### end Alembic commands ###
